### ISSUE TITLE
Error: Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by toddmedema** [pbeshai/react-url-query#15]
Trying to get this set up for the first time, running into this warning:

`bundle.js:1008 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

Error location in code (when viewed in Chrome Console):
```
RouterToUrlQuery.propTypes = {
  children: _react.PropTypes.node
};
```

Dependency slice:
```
  "dependencies": {
    "history": "^4.6.1",
    "react": "^15.5.4",
    "react-url-query": "^1.1.1",
    "redux": "^3.6.0",
    "typescript": "^2.2.2",
    "webpack": "^2.4.1",
  }
```

Which is weird, since the Redux example seems to run fine. Any ideas?

If it helps, here's the link to the branch: https://github.com/ExpeditionRPG/expedition-cards/tree/history

**Comment by antsav** [comment]
+1

**Comment by pbeshai** [comment]
Fixed in 1.1.2

**Comment by toddmedema** [comment]
Thank you! :)

**Comment by maxmoeschinger** [comment]
I am still getting the error. from file addUrlProps.js I am on version 1.1.3

**Comment by pbeshai** [comment]
Sorry, I missed a couple imports. Should be fixed now in 1.1.4.

**Comment by maxmoeschinger** [comment]
I must say you have some serious response time ;)
